//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMarafons.Table
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARAFON
    {
        public int UID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> DLINA { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<decimal> VZNOS { get; set; }
    }
}
