//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMarafons.Table
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MARAFON_DBEntities : DbContext
    {
        public MARAFON_DBEntities()
            : base("name=MARAFON_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MARAFON> MARAFON { get; set; }
        public virtual DbSet<MARAFON_UCHASTIE> MARAFON_UCHASTIE { get; set; }
        public virtual DbSet<SPORTMENS> SPORTMENS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TYPE> TYPE { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<ZRITELI> ZRITELI { get; set; }
    }
}
