//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMarafons.Table
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual TYPE TYPE1 { get; set; }
    }
}
